version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    ECR_REGISTRY: "420933050007.dkr.ecr.ap-south-1.amazonaws.com"
    ECR_URI: "420933050007.dkr.ecr.ap-south-1.amazonaws.com/zt-charts"

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - IMAGE_TAG=build-$(date +%Y%m%d-%H%M%S)
      - echo "登录ECR注册表: $ECR_REGISTRY"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo "创建Dockerfile..."
      - echo "FROM node:18-alpine" > Dockerfile
      - echo "WORKDIR /app" >> Dockerfile
      - echo "COPY package*.json ./" >> Dockerfile
      - echo "COPY index.js ./" >> Dockerfile
      - echo "RUN npm install" >> Dockerfile
      - echo "EXPOSE 3000" >> Dockerfile
      - echo "CMD [\"node\", \"index.js\"]" >> Dockerfile
      - docker build -t $ECR_URI:$IMAGE_TAG .
      - docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest

  post_build:
    commands:
      - echo "推送镜像到ECR"
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
      - echo "完成: $ECR_URI:$IMAGE_TAG"