version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"

phases:
  pre_build:
    commands:
      - ECR_REGISTRY="420933050007.dkr.ecr.ap-south-1.amazonaws.com"
      - ECR_URI="420933050007.dkr.ecr.ap-south-1.amazonaws.com/zt-charts"
      - IMAGE_TAG="build-$(date +%Y%m%d-%H%M%S)"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo "FROM node:18-alpine" > Dockerfile
      - echo "WORKDIR /app" >> Dockerfile
      - echo "COPY package*.json ./" >> Dockerfile
      - echo "COPY index.js ./" >> Dockerfile
      - echo "RUN npm install express@^4.18.0" >> Dockerfile
      - echo "EXPOSE 3000" >> Dockerfile
      - echo "CMD [\"node\", \"index.js\"]" >> Dockerfile
      - docker build -t $ECR_URI:$IMAGE_TAG .
      - docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:nodejs-app

  post_build:
    commands:
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:nodejs-app
      - echo "构建完成"