version: 0.2

phases:
  pre_build:
    commands:
      - echo "=== è®¾ç½®ECRç›®çš„åœ° ==="
      - ECR_URI=420933050007.dkr.ecr.ap-south-1.amazonaws.com/zt-charts
      - IMAGE_TAG=build-$(date +%Y%m%d-%H%M%S)
      - echo "ç›®çš„åœ°: $ECR_URI"
      - echo "é•œåƒæ ‡ç­¾: $IMAGE_TAG"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 420933050007.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "=== æž„å»ºDockeré•œåƒ ==="
      - echo "ç”ŸæˆDockerfile..."
      - cat > Dockerfile << EOF
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
COPY index.js ./
RUN npm ci --only=production
EXPOSE 3000
USER node
CMD ["node", "index.js"]
EOF
      - docker build -t $ECR_URI:$IMAGE_TAG .
      - docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest

  post_build:
    commands:
      - echo "=== æŽ¨é€åˆ°ECR ==="
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
      - echo "âœ… æž„å»ºå®Œæˆ!"
      - echo "ðŸ“¦ é•œåƒåœ°å€: $ECR_URI:$IMAGE_TAG"
      - echo "â° æž„å»ºæ—¶é—´: $(date)"

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1