version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    ECR_URI: "420933050007.dkr.ecr.ap-south-1.amazonaws.com/zt-charts"

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - IMAGE_TAG=build-$(date +%Y%m%d-%H%M%S)
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 420933050007.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - cat > Dockerfile << EOF
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
COPY index.js ./
RUN npm install
EXPOSE 3000
CMD ["node", "index.js"]
EOF
      - docker build -t $ECR_URI:$IMAGE_TAG .
      - docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest

  post_build:
    commands:
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
      - echo "构建完成: $ECR_URI:$IMAGE_TAG"