version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    ECR_REPOSITORY: "zt-charts"
    ECR_URI: "420933050007.dkr.ecr.ap-south-1.amazonaws.com/zt-charts"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "å®‰è£…é˜¶æ®µå¼€å§‹..."

  pre_build:
    commands:
      - echo "é¢„æž„å»ºé˜¶æ®µå¼€å§‹"
      - IMAGE_TAG=version-$(date +%Y%m%d-%H%M%S)
      - echo "ECR URI: $ECR_URI"
      - echo "é•œåƒæ ‡ç­¾: $IMAGE_TAG"
      - echo "æ­£åœ¨ç™»å½•ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 420933050007.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo "æž„å»ºé˜¶æ®µå¼€å§‹"
      - echo "åˆ›å»ºDockerfile..."
      - cat > Dockerfile << EOF
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY index.js ./
EXPOSE 3000
CMD ["node", "index.js"]
EOF
      - echo "æž„å»ºDockeré•œåƒ..."
      - docker build -t $ECR_URI:$IMAGE_TAG .
      - docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest

  post_build:
    commands:
      - echo "åŽæž„å»ºé˜¶æ®µå¼€å§‹"
      - echo "æŽ¨é€é•œåƒåˆ°ECR..."
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
      - echo "âœ… æž„å»ºæˆåŠŸå®Œæˆ!"
      - echo "ðŸ“¦ é•œåƒåœ°å€: $ECR_URI:$IMAGE_TAG"
      - echo "ðŸ”– æœ€æ–°æ ‡ç­¾: $ECR_URI:latest"

artifacts:
  files:
    - "Dockerfile"
  base-directory: .